/// Flutter icons BottomNavBarIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  BottomNavBarIcons
///      fonts:
///       - asset: fonts/BottomNavBarIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class BottomNavBarIcons {
  BottomNavBarIcons._();

  static const _kFontFam = 'BottomNavBarIcons';
  static const _kFontPkg = null;

  static const IconData quiz = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reminder = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData statistics = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData word = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
